
4.4-ubuntu1804:
  extends: .docker
  stage: ubuntu1804
  variables:
    MAJOR_VERSION: 4
    VERSION: "4.4"
    LONG_VERSION: "4.4"
    VARIANT: ubuntu1804
    PARENT: "ubuntu"
    ISPARENT: "False"

4.4-ubuntu2004:
  extends: .docker
  stage: ubuntu2004
  variables:
    MAJOR_VERSION: 4
    VERSION: "4.4"
    LONG_VERSION: "4.4"
    VARIANT: ubuntu2004
    PARENT: "ubuntu"
    ISPARENT: "True"

4.4-alpine312:
  extends: .docker
  stage: alpine312
  variables:
    MAJOR_VERSION: 4
    VERSION: "4.4"
    LONG_VERSION: "4.4"
    VARIANT: alpine312
    PARENT: "alpine"
    ISPARENT: "False"

4.4-alpine38:
  extends: .docker
  stage: alpine38
  variables:
    MAJOR_VERSION: 4
    VERSION: "4.4"
    LONG_VERSION: "4.4"
    VARIANT: alpine38
    PARENT: "alpine"
    ISPARENT: "True"

4.4-centos7:
  extends: .docker
  stage: centos7
  variables:
    MAJOR_VERSION: 4
    VERSION: "4.4"
    LONG_VERSION: "4.4"
    VARIANT: centos7
    PARENT: "centos"
    ISPARENT: "False"

4.4-centos8:
  extends: .docker
  stage: centos8
  variables:
    MAJOR_VERSION: 4
    VERSION: "4.4"
    LONG_VERSION: "4.4"
    VARIANT: centos8
    PARENT: "centos"
    ISPARENT: "True"

4.4-scratch312:
  extends: .docker
  stage: scratch312
  variables:
    MAJOR_VERSION: 4
    VERSION: "4.4"
    LONG_VERSION: "4.4"
    VARIANT: scratch312
    PARENT: "scratch"
    ISPARENT: "False"

4.4-scratch38:
  extends: .docker
  stage: scratch38
  variables:
    MAJOR_VERSION: 4
    VERSION: "4.4"
    LONG_VERSION: "4.4"
    VARIANT: scratch38
    PARENT: "scratch"
    ISPARENT: "True"

4.4-vaapi1804:
  extends: .docker
  stage: vaapi1804
  variables:
    MAJOR_VERSION: 4
    VERSION: "4.4"
    LONG_VERSION: "4.4"
    VARIANT: vaapi1804
    PARENT: "vaapi"
    ISPARENT: "False"

4.4-vaapi2004:
  extends: .docker
  stage: vaapi2004
  variables:
    MAJOR_VERSION: 4
    VERSION: "4.4"
    LONG_VERSION: "4.4"
    VARIANT: vaapi2004
    PARENT: "vaapi"
    ISPARENT: "True"

4.4-nvidia2004:
  extends: .docker
  stage: nvidia2004
  variables:
    MAJOR_VERSION: 4
    VERSION: "4.4"
    LONG_VERSION: "4.4"
    VARIANT: nvidia2004
    PARENT: "nvidia"
    ISPARENT: "True"

4.3.2-ubuntu1804:
  extends: .docker
  stage: ubuntu1804
  variables:
    MAJOR_VERSION: 4
    VERSION: "4.3"
    LONG_VERSION: "4.3.2"
    VARIANT: ubuntu1804
    PARENT: "ubuntu"
    ISPARENT: "False"

4.3.2-ubuntu2004:
  extends: .docker
  stage: ubuntu2004
  variables:
    MAJOR_VERSION: 4
    VERSION: "4.3"
    LONG_VERSION: "4.3.2"
    VARIANT: ubuntu2004
    PARENT: "ubuntu"
    ISPARENT: "True"

4.3.2-alpine312:
  extends: .docker
  stage: alpine312
  variables:
    MAJOR_VERSION: 4
    VERSION: "4.3"
    LONG_VERSION: "4.3.2"
    VARIANT: alpine312
    PARENT: "alpine"
    ISPARENT: "False"

4.3.2-alpine38:
  extends: .docker
  stage: alpine38
  variables:
    MAJOR_VERSION: 4
    VERSION: "4.3"
    LONG_VERSION: "4.3.2"
    VARIANT: alpine38
    PARENT: "alpine"
    ISPARENT: "True"

4.3.2-centos7:
  extends: .docker
  stage: centos7
  variables:
    MAJOR_VERSION: 4
    VERSION: "4.3"
    LONG_VERSION: "4.3.2"
    VARIANT: centos7
    PARENT: "centos"
    ISPARENT: "False"

4.3.2-centos8:
  extends: .docker
  stage: centos8
  variables:
    MAJOR_VERSION: 4
    VERSION: "4.3"
    LONG_VERSION: "4.3.2"
    VARIANT: centos8
    PARENT: "centos"
    ISPARENT: "True"

4.3.2-scratch312:
  extends: .docker
  stage: scratch312
  variables:
    MAJOR_VERSION: 4
    VERSION: "4.3"
    LONG_VERSION: "4.3.2"
    VARIANT: scratch312
    PARENT: "scratch"
    ISPARENT: "False"

4.3.2-scratch38:
  extends: .docker
  stage: scratch38
  variables:
    MAJOR_VERSION: 4
    VERSION: "4.3"
    LONG_VERSION: "4.3.2"
    VARIANT: scratch38
    PARENT: "scratch"
    ISPARENT: "True"

4.3.2-vaapi1804:
  extends: .docker
  stage: vaapi1804
  variables:
    MAJOR_VERSION: 4
    VERSION: "4.3"
    LONG_VERSION: "4.3.2"
    VARIANT: vaapi1804
    PARENT: "vaapi"
    ISPARENT: "False"

4.3.2-vaapi2004:
  extends: .docker
  stage: vaapi2004
  variables:
    MAJOR_VERSION: 4
    VERSION: "4.3"
    LONG_VERSION: "4.3.2"
    VARIANT: vaapi2004
    PARENT: "vaapi"
    ISPARENT: "True"

4.3.2-nvidia2004:
  extends: .docker
  stage: nvidia2004
  variables:
    MAJOR_VERSION: 4
    VERSION: "4.3"
    LONG_VERSION: "4.3.2"
    VARIANT: nvidia2004
    PARENT: "nvidia"
    ISPARENT: "True"

4.2.4-ubuntu1804:
  extends: .docker
  stage: ubuntu1804
  variables:
    MAJOR_VERSION: 4
    VERSION: "4.2"
    LONG_VERSION: "4.2.4"
    VARIANT: ubuntu1804
    PARENT: "ubuntu"
    ISPARENT: "False"

4.2.4-ubuntu2004:
  extends: .docker
  stage: ubuntu2004
  variables:
    MAJOR_VERSION: 4
    VERSION: "4.2"
    LONG_VERSION: "4.2.4"
    VARIANT: ubuntu2004
    PARENT: "ubuntu"
    ISPARENT: "True"

4.2.4-alpine312:
  extends: .docker
  stage: alpine312
  variables:
    MAJOR_VERSION: 4
    VERSION: "4.2"
    LONG_VERSION: "4.2.4"
    VARIANT: alpine312
    PARENT: "alpine"
    ISPARENT: "True"

4.2.4-centos7:
  extends: .docker
  stage: centos7
  variables:
    MAJOR_VERSION: 4
    VERSION: "4.2"
    LONG_VERSION: "4.2.4"
    VARIANT: centos7
    PARENT: "centos"
    ISPARENT: "False"

4.2.4-centos8:
  extends: .docker
  stage: centos8
  variables:
    MAJOR_VERSION: 4
    VERSION: "4.2"
    LONG_VERSION: "4.2.4"
    VARIANT: centos8
    PARENT: "centos"
    ISPARENT: "True"

4.2.4-scratch312:
  extends: .docker
  stage: scratch312
  variables:
    MAJOR_VERSION: 4
    VERSION: "4.2"
    LONG_VERSION: "4.2.4"
    VARIANT: scratch312
    PARENT: "scratch"
    ISPARENT: "True"

4.2.4-vaapi2004:
  extends: .docker
  stage: vaapi2004
  variables:
    MAJOR_VERSION: 4
    VERSION: "4.2"
    LONG_VERSION: "4.2.4"
    VARIANT: vaapi2004
    PARENT: "vaapi"
    ISPARENT: "True"

4.2.4-nvidia2004:
  extends: .docker
  stage: nvidia2004
  variables:
    MAJOR_VERSION: 4
    VERSION: "4.2"
    LONG_VERSION: "4.2.4"
    VARIANT: nvidia2004
    PARENT: "nvidia"
    ISPARENT: "True"

4.1.6-ubuntu1804:
  extends: .docker
  stage: ubuntu1804
  variables:
    MAJOR_VERSION: 4
    VERSION: "4.1"
    LONG_VERSION: "4.1.6"
    VARIANT: ubuntu1804
    PARENT: "ubuntu"
    ISPARENT: "False"

4.1.6-ubuntu2004:
  extends: .docker
  stage: ubuntu2004
  variables:
    MAJOR_VERSION: 4
    VERSION: "4.1"
    LONG_VERSION: "4.1.6"
    VARIANT: ubuntu2004
    PARENT: "ubuntu"
    ISPARENT: "True"

4.1.6-alpine312:
  extends: .docker
  stage: alpine312
  variables:
    MAJOR_VERSION: 4
    VERSION: "4.1"
    LONG_VERSION: "4.1.6"
    VARIANT: alpine312
    PARENT: "alpine"
    ISPARENT: "True"

4.1.6-centos7:
  extends: .docker
  stage: centos7
  variables:
    MAJOR_VERSION: 4
    VERSION: "4.1"
    LONG_VERSION: "4.1.6"
    VARIANT: centos7
    PARENT: "centos"
    ISPARENT: "False"

4.1.6-centos8:
  extends: .docker
  stage: centos8
  variables:
    MAJOR_VERSION: 4
    VERSION: "4.1"
    LONG_VERSION: "4.1.6"
    VARIANT: centos8
    PARENT: "centos"
    ISPARENT: "True"

4.1.6-scratch312:
  extends: .docker
  stage: scratch312
  variables:
    MAJOR_VERSION: 4
    VERSION: "4.1"
    LONG_VERSION: "4.1.6"
    VARIANT: scratch312
    PARENT: "scratch"
    ISPARENT: "True"

4.1.6-vaapi2004:
  extends: .docker
  stage: vaapi2004
  variables:
    MAJOR_VERSION: 4
    VERSION: "4.1"
    LONG_VERSION: "4.1.6"
    VARIANT: vaapi2004
    PARENT: "vaapi"
    ISPARENT: "True"

4.1.6-nvidia2004:
  extends: .docker
  stage: nvidia2004
  variables:
    MAJOR_VERSION: 4
    VERSION: "4.1"
    LONG_VERSION: "4.1.6"
    VARIANT: nvidia2004
    PARENT: "nvidia"
    ISPARENT: "True"

4.0.6-ubuntu1804:
  extends: .docker
  stage: ubuntu1804
  variables:
    MAJOR_VERSION: 4
    VERSION: "4.0"
    LONG_VERSION: "4.0.6"
    VARIANT: ubuntu1804
    PARENT: "ubuntu"
    ISPARENT: "False"

4.0.6-ubuntu2004:
  extends: .docker
  stage: ubuntu2004
  variables:
    MAJOR_VERSION: 4
    VERSION: "4.0"
    LONG_VERSION: "4.0.6"
    VARIANT: ubuntu2004
    PARENT: "ubuntu"
    ISPARENT: "True"

4.0.6-alpine312:
  extends: .docker
  stage: alpine312
  variables:
    MAJOR_VERSION: 4
    VERSION: "4.0"
    LONG_VERSION: "4.0.6"
    VARIANT: alpine312
    PARENT: "alpine"
    ISPARENT: "True"

4.0.6-centos7:
  extends: .docker
  stage: centos7
  variables:
    MAJOR_VERSION: 4
    VERSION: "4.0"
    LONG_VERSION: "4.0.6"
    VARIANT: centos7
    PARENT: "centos"
    ISPARENT: "False"

4.0.6-centos8:
  extends: .docker
  stage: centos8
  variables:
    MAJOR_VERSION: 4
    VERSION: "4.0"
    LONG_VERSION: "4.0.6"
    VARIANT: centos8
    PARENT: "centos"
    ISPARENT: "True"

4.0.6-scratch312:
  extends: .docker
  stage: scratch312
  variables:
    MAJOR_VERSION: 4
    VERSION: "4.0"
    LONG_VERSION: "4.0.6"
    VARIANT: scratch312
    PARENT: "scratch"
    ISPARENT: "True"

4.0.6-vaapi2004:
  extends: .docker
  stage: vaapi2004
  variables:
    MAJOR_VERSION: 4
    VERSION: "4.0"
    LONG_VERSION: "4.0.6"
    VARIANT: vaapi2004
    PARENT: "vaapi"
    ISPARENT: "True"

4.0.6-nvidia2004:
  extends: .docker
  stage: nvidia2004
  variables:
    MAJOR_VERSION: 4
    VERSION: "4.0"
    LONG_VERSION: "4.0.6"
    VARIANT: nvidia2004
    PARENT: "nvidia"
    ISPARENT: "True"

3.4.8-ubuntu1804:
  extends: .docker
  stage: ubuntu1804
  variables:
    MAJOR_VERSION: 3
    VERSION: "3.4"
    LONG_VERSION: "3.4.8"
    VARIANT: ubuntu1804
    PARENT: "ubuntu"
    ISPARENT: "False"

3.4.8-ubuntu2004:
  extends: .docker
  stage: ubuntu2004
  variables:
    MAJOR_VERSION: 3
    VERSION: "3.4"
    LONG_VERSION: "3.4.8"
    VARIANT: ubuntu2004
    PARENT: "ubuntu"
    ISPARENT: "True"

3.4.8-alpine312:
  extends: .docker
  stage: alpine312
  variables:
    MAJOR_VERSION: 3
    VERSION: "3.4"
    LONG_VERSION: "3.4.8"
    VARIANT: alpine312
    PARENT: "alpine"
    ISPARENT: "True"

3.4.8-centos7:
  extends: .docker
  stage: centos7
  variables:
    MAJOR_VERSION: 3
    VERSION: "3.4"
    LONG_VERSION: "3.4.8"
    VARIANT: centos7
    PARENT: "centos"
    ISPARENT: "False"

3.4.8-centos8:
  extends: .docker
  stage: centos8
  variables:
    MAJOR_VERSION: 3
    VERSION: "3.4"
    LONG_VERSION: "3.4.8"
    VARIANT: centos8
    PARENT: "centos"
    ISPARENT: "True"

3.4.8-scratch312:
  extends: .docker
  stage: scratch312
  variables:
    MAJOR_VERSION: 3
    VERSION: "3.4"
    LONG_VERSION: "3.4.8"
    VARIANT: scratch312
    PARENT: "scratch"
    ISPARENT: "True"

3.4.8-vaapi2004:
  extends: .docker
  stage: vaapi2004
  variables:
    MAJOR_VERSION: 3
    VERSION: "3.4"
    LONG_VERSION: "3.4.8"
    VARIANT: vaapi2004
    PARENT: "vaapi"
    ISPARENT: "True"

3.4.8-nvidia2004:
  extends: .docker
  stage: nvidia2004
  variables:
    MAJOR_VERSION: 3
    VERSION: "3.4"
    LONG_VERSION: "3.4.8"
    VARIANT: nvidia2004
    PARENT: "nvidia"
    ISPARENT: "True"

3.3.9-ubuntu1804:
  extends: .docker
  stage: ubuntu1804
  variables:
    MAJOR_VERSION: 3
    VERSION: "3.3"
    LONG_VERSION: "3.3.9"
    VARIANT: ubuntu1804
    PARENT: "ubuntu"
    ISPARENT: "False"

3.3.9-ubuntu2004:
  extends: .docker
  stage: ubuntu2004
  variables:
    MAJOR_VERSION: 3
    VERSION: "3.3"
    LONG_VERSION: "3.3.9"
    VARIANT: ubuntu2004
    PARENT: "ubuntu"
    ISPARENT: "True"

3.3.9-alpine312:
  extends: .docker
  stage: alpine312
  variables:
    MAJOR_VERSION: 3
    VERSION: "3.3"
    LONG_VERSION: "3.3.9"
    VARIANT: alpine312
    PARENT: "alpine"
    ISPARENT: "True"

3.3.9-centos7:
  extends: .docker
  stage: centos7
  variables:
    MAJOR_VERSION: 3
    VERSION: "3.3"
    LONG_VERSION: "3.3.9"
    VARIANT: centos7
    PARENT: "centos"
    ISPARENT: "False"

3.3.9-centos8:
  extends: .docker
  stage: centos8
  variables:
    MAJOR_VERSION: 3
    VERSION: "3.3"
    LONG_VERSION: "3.3.9"
    VARIANT: centos8
    PARENT: "centos"
    ISPARENT: "True"

3.3.9-scratch312:
  extends: .docker
  stage: scratch312
  variables:
    MAJOR_VERSION: 3
    VERSION: "3.3"
    LONG_VERSION: "3.3.9"
    VARIANT: scratch312
    PARENT: "scratch"
    ISPARENT: "True"

3.3.9-vaapi2004:
  extends: .docker
  stage: vaapi2004
  variables:
    MAJOR_VERSION: 3
    VERSION: "3.3"
    LONG_VERSION: "3.3.9"
    VARIANT: vaapi2004
    PARENT: "vaapi"
    ISPARENT: "True"

3.3.9-nvidia2004:
  extends: .docker
  stage: nvidia2004
  variables:
    MAJOR_VERSION: 3
    VERSION: "3.3"
    LONG_VERSION: "3.3.9"
    VARIANT: nvidia2004
    PARENT: "nvidia"
    ISPARENT: "True"

3.2.15-ubuntu2004:
  extends: .docker
  stage: ubuntu2004
  variables:
    MAJOR_VERSION: 3
    VERSION: "3.2"
    LONG_VERSION: "3.2.15"
    VARIANT: ubuntu2004
    PARENT: "ubuntu"
    ISPARENT: "True"

3.2.15-alpine38:
  extends: .docker
  stage: alpine38
  variables:
    MAJOR_VERSION: 3
    VERSION: "3.2"
    LONG_VERSION: "3.2.15"
    VARIANT: alpine38
    PARENT: "alpine"
    ISPARENT: "True"

3.2.15-centos7:
  extends: .docker
  stage: centos7
  variables:
    MAJOR_VERSION: 3
    VERSION: "3.2"
    LONG_VERSION: "3.2.15"
    VARIANT: centos7
    PARENT: "centos"
    ISPARENT: "True"

3.2.15-scratch38:
  extends: .docker
  stage: scratch38
  variables:
    MAJOR_VERSION: 3
    VERSION: "3.2"
    LONG_VERSION: "3.2.15"
    VARIANT: scratch38
    PARENT: "scratch"
    ISPARENT: "True"

3.2.15-vaapi2004:
  extends: .docker
  stage: vaapi2004
  variables:
    MAJOR_VERSION: 3
    VERSION: "3.2"
    LONG_VERSION: "3.2.15"
    VARIANT: vaapi2004
    PARENT: "vaapi"
    ISPARENT: "True"
